#!/usr/bin/env python3
"""
update_literature_review.py -- Quarterly literature review improvement workflow.

This script produces a structured agenda for updating the literature review,
checks source registry completeness, and reports gaps.

Usage:
    python3 Scripts/update_literature_review.py
    python3 Scripts/update_literature_review.py --output agenda.md
"""

import re
import sys
import json
import pathlib
import datetime
from typing import List, Tuple

ROOT = pathlib.Path(__file__).parent.parent
REGISTRY = ROOT / "Mem" / "source-registry.md"
LIT_STATE = ROOT / "Mem" / "literature-review-state.md"

# Search terms to check against known new domains each quarter
QUARTERLY_CHECKS = [
    ("Swiss e-government", ["EMBAG", "eGovernment Suisse", "E-Government Strategie"]),
    ("German OZG/FITKO", ["OZG", "FITKO", "openCode", "ZenDiS"]),
    ("EU legislation", ["Data Act", "AI Act", "Interoperable Europe", "NIS2"]),
    ("Sovereign Cloud Stack", ["SCS", "OpenStack", "OSBA"]),
    ("GovStack", ["ITU", "DIAL", "building block"]),
    ("Decidim / CONSUL", ["Decidim", "CONSUL Democracy", "participatory"]),
    ("Matrix / Element", ["Matrix protocol", "BundesMessenger"]),
    ("Nextcloud", ["Nextcloud", "file sync", "collaboration"]),
    ("GIS open-source", ["QGIS", "GeoServer", "OpenStreetMap"]),
    ("Security", ["BSI", "NIS2", "SBOM", "CVE"]),
    ("TCO studies", ["total cost", "TCO", "migration cost"]),
    ("eCH standards", ["eCH", "Swiss XML", "interoperability Switzerland"]),
    ("Academic e-gov", ["GIQ", "ISM", "EJEG", "maturity model"]),
    ("OSOR", ["Open Source Observatory", "OSOR", "JoinUp"]),
    ("UN E-Government", ["UN Survey", "UNDESA"]),
]


def parse_registry_ids(text: str) -> List[str]:
    return re.findall(r"^### \[(\d+)\]", text, re.MULTILINE)


def parse_unverified(text: str) -> List[Tuple[str, str]]:
    results = []
    for m in re.finditer(r"### \[(\d+)\][^\n]*\n(?:[^#]|\n)*?\*\*Verifikationsstatus:\*\* unverified", text):
        id_m = re.search(r"\[(\d+)\]", m.group(0))
        title_m = re.search(r"\*\*Dokumenttitel:\*\* (.+)", m.group(0))
        if id_m and title_m:
            results.append((id_m.group(1), title_m.group(1).strip()))
    return results


def build_agenda() -> str:
    today = datetime.date.today().isoformat()
    next_review = (datetime.date.today() + datetime.timedelta(days=90)).isoformat()

    registry_text = REGISTRY.read_text(encoding="utf-8") if REGISTRY.exists() else ""
    lit_text = LIT_STATE.read_text(encoding="utf-8") if LIT_STATE.exists() else ""

    ids = parse_registry_ids(registry_text)
    unverified = parse_unverified(registry_text)

    lines = [
        f"# Quarterly Literature Review Agenda",
        f"",
        f"**Generated:** {today}  ",
        f"**Next review:** {next_review}  ",
        f"**Registry entries:** {len(ids)}  ",
        f"**Unverified sources:** {len(unverified)}  ",
        f"",
        f"---",
        f"",
        f"## 1. Unverified Sources to Confirm",
        f"",
    ]

    if unverified:
        for src_id, title in unverified:
            lines.append(f"- [ ] [{src_id}] {title} — verify URL and metadata")
    else:
        lines.append("- [x] All sources verified in current registry.")

    lines += [
        f"",
        f"## 2. Quarterly Search Agenda",
        f"",
        f"For each domain below, search for publications from the last 90 days:",
        f"",
    ]

    for domain, terms in QUARTERLY_CHECKS:
        lines.append(f"### {domain}")
        for t in terms:
            lines.append(f"- [ ] Search: `{t}` (policy docs, press releases, academic papers)")
        lines.append("")

    lines += [
        f"## 3. Gap Areas to Address",
        f"",
        f"Priority gaps from current literature review state:",
        f"",
        f"- [ ] OSOR Annual Report (latest) — add as source [54]",
        f"- [ ] GovStack Specification v1.0 — add as source [56]",
        f"- [ ] EU AI Act implementation guidance for municipalities — add as source [60]",
        f"- [ ] Citizen satisfaction survey framework (design for v1.0 appendix)",
        f"- [ ] Longitudinal follow-up on 3 v0.2.0 case studies (Schaffhausen, Biberach, Rosenheim)",
        f"",
        f"## 4. Version Targets",
        f"",
        f"| Target | Criterion |",
        f"|---|---|",
        f"| v0.3.0 | OSOR, GovStack spec, EU AI Act integrated; 2 new case studies |",
        f"| v1.0.0 | All sources verified; citizen survey framework; peer-reviewed |",
        f"",
        f"---",
        f"*Generated by `Scripts/update_literature_review.py`*",
    ]

    return "\n".join(lines)


def main():
    import argparse
    parser = argparse.ArgumentParser(description="Generate quarterly literature review agenda")
    parser.add_argument("--output", help="Write agenda to this file (default: stdout)")
    args = parser.parse_args()

    agenda = build_agenda()

    if args.output:
        pathlib.Path(args.output).write_text(agenda, encoding="utf-8")
        print(f"Agenda written to {args.output}")
    else:
        print(agenda)


if __name__ == "__main__":
    main()
